print("did you save the password in the clipboard?")
password = input("Enter the password: ")
print("password: " + password)
print("password length: " + str(len(password)))
print("do you want to save the password in to a file?")
save_password = input("y/n: ")
if save_password == "y":
    print("pls enter the file name: ")
    file_name = input("file name: ")
    file = open(file_name, "w")
    file.write(password)
    file.close()
    print("password saved in file: " + file_name)